// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/IRPrintingPasses.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("convolve.opt.lr.ll", getGlobalContext());
 mod->setDataLayout("0x4383fd0");
 mod->setTargetTriple("x86_64-unknown-linux-gnu");
 
 // Type Definitions
 std::vector<Type*>FuncTy_0_args;
 PointerType* PointerTy_1 = PointerType::get(IntegerType::get(mod->getContext(), 8), 0);
 
 FuncTy_0_args.push_back(PointerTy_1);
 FuncTy_0_args.push_back(PointerTy_1);
 PointerType* PointerTy_2 = PointerType::get(Type::getFloatTy(mod->getContext()), 0);
 
 FuncTy_0_args.push_back(PointerTy_2);
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_0 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_0_args,
  /*isVarArg=*/false);
 
 std::vector<Type*>FuncTy_4_args;
 FuncTy_4_args.push_back(OtherTy_5);
 FuncTy_4_args.push_back(IntegerType::get(mod->getContext(), 64));
 FuncTy_4_args.push_back(OtherTy_5);
 FuncTy_4_args.push_back(OtherTy_5);
 FunctionType* FuncTy_4 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_4_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_3 = PointerType::get(FuncTy_4, 0);
 
 std::vector<Type*>FuncTy_6_args;
 FuncTy_6_args.push_back(OtherTy_5);
 FuncTy_6_args.push_back(OtherTy_5);
 FuncTy_6_args.push_back(OtherTy_5);
 FunctionType* FuncTy_6 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_6_args,
  /*isVarArg=*/false);
 
 std::vector<Type*>FuncTy_7_args;
 PointerType* PointerTy_8 = PointerType::get(PointerTy_1, 0);
 
 FuncTy_7_args.push_back(PointerTy_8);
 FuncTy_7_args.push_back(PointerTy_8);
 FuncTy_7_args.push_back(PointerTy_2);
 FuncTy_7_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_7_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_7_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_7 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_7_args,
  /*isVarArg=*/false);
 
 std::vector<Type*>FuncTy_9_args;
 FuncTy_9_args.push_back(PointerTy_1);
 FuncTy_9_args.push_back(PointerTy_1);
 FuncTy_9_args.push_back(PointerTy_2);
 FuncTy_9_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_9_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_9_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_9 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_9_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_10 = PointerType::get(FuncTy_0, 0);
 
 PointerType* PointerTy_11 = PointerType::get(FuncTy_7, 0);
 
 
 // Function Declarations
 
 Function* func_filter_kernel = mod->getFunction("filter_kernel");
 if (!func_filter_kernel) {
 func_filter_kernel = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"filter_kernel", mod); 
 func_filter_kernel->setCallingConv(CallingConv::C);
 }
 AttributeSet func_filter_kernel_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_filter_kernel_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_filter_kernel->setAttributes(func_filter_kernel_PAL);
 
 Function* func_llvm_dbg_declare = mod->getFunction("llvm.dbg.declare");
 if (!func_llvm_dbg_declare) {
 func_llvm_dbg_declare = Function::Create(
  /*Type=*/FuncTy_6,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"llvm.dbg.declare", mod); // (external, no body)
 func_llvm_dbg_declare->setCallingConv(CallingConv::C);
 }
 AttributeSet func_llvm_dbg_declare_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::ReadNone);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_llvm_dbg_declare_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_llvm_dbg_declare->setAttributes(func_llvm_dbg_declare_PAL);
 
 Function* func_filter_kernel_2d = mod->getFunction("filter_kernel_2d");
 if (!func_filter_kernel_2d) {
 func_filter_kernel_2d = Function::Create(
  /*Type=*/FuncTy_7,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"filter_kernel_2d", mod); 
 func_filter_kernel_2d->setCallingConv(CallingConv::C);
 }
 AttributeSet func_filter_kernel_2d_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_filter_kernel_2d_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_filter_kernel_2d->setAttributes(func_filter_kernel_2d_PAL);
 
 Function* func_convolve_arr_linear = mod->getFunction("convolve_arr_linear");
 if (!func_convolve_arr_linear) {
 func_convolve_arr_linear = Function::Create(
  /*Type=*/FuncTy_9,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"convolve_arr_linear", mod); 
 func_convolve_arr_linear->setCallingConv(CallingConv::C);
 }
 AttributeSet func_convolve_arr_linear_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_convolve_arr_linear_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_convolve_arr_linear->setAttributes(func_convolve_arr_linear_PAL);
 
 Function* func_convolve_arr_indirection = mod->getFunction("convolve_arr_indirection");
 if (!func_convolve_arr_indirection) {
 func_convolve_arr_indirection = Function::Create(
  /*Type=*/FuncTy_7,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"convolve_arr_indirection", mod); 
 func_convolve_arr_indirection->setCallingConv(CallingConv::C);
 }
 AttributeSet func_convolve_arr_indirection_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_convolve_arr_indirection_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_convolve_arr_indirection->setAttributes(func_convolve_arr_indirection_PAL);
 
 Function* func_convolve_loop_nest = mod->getFunction("convolve_loop_nest");
 if (!func_convolve_loop_nest) {
 func_convolve_loop_nest = Function::Create(
  /*Type=*/FuncTy_7,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"convolve_loop_nest", mod); 
 func_convolve_loop_nest->setCallingConv(CallingConv::C);
 }
 AttributeSet func_convolve_loop_nest_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_convolve_loop_nest_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_convolve_loop_nest->setAttributes(func_convolve_loop_nest_PAL);
 
 Function* func_llvm_dbg_value = mod->getFunction("llvm.dbg.value");
 if (!func_llvm_dbg_value) {
 func_llvm_dbg_value = Function::Create(
  /*Type=*/FuncTy_4,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"llvm.dbg.value", mod); // (external, no body)
 func_llvm_dbg_value->setCallingConv(CallingConv::C);
 }
 AttributeSet func_llvm_dbg_value_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::ReadNone);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_llvm_dbg_value_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_llvm_dbg_value->setAttributes(func_llvm_dbg_value_PAL);
 
 // Global Variable Declarations

 
 // Constant Definitions
 ConstantInt* const_int64_12 = ConstantInt::get(mod->getContext(), APInt(64, StringRef("0"), 10));
 ConstantInt* const_int32_13 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("2"), 10));
 ConstantInt* const_int32_14 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("0"), 10));
 ConstantFP* const_float_15 = ConstantFP::get(mod->getContext(), APFloat(0.000000e+00f));
 ConstantInt* const_int64_16 = ConstantInt::get(mod->getContext(), APInt(64, StringRef("1"), 10));
 ConstantInt* const_int32_17 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 
 // Global Variable Definitions
 
 // Function Definitions
 
 // Function: filter_kernel (func_filter_kernel)
 {
  Function::arg_iterator args = func_filter_kernel->arg_begin();
  Value* ptr_in = args++;
  ptr_in->setName("in");
  Value* ptr_out = args++;
  ptr_out->setName("out");
  Value* ptr_kernel = args++;
  ptr_kernel->setName("kernel");
  Value* int32_kn = args++;
  int32_kn->setName("kn");
  Value* int32_m = args++;
  int32_m->setName("m");
  Value* int32_n = args++;
  int32_n->setName("n");
  Value* int32_size_x = args++;
  int32_size_x->setName("size_x");
  Value* int32_size_y = args++;
  int32_size_y->setName("size_y");
  
  BasicBlock* label_entry = BasicBlock::Create(mod->getContext(), "entry",func_filter_kernel,0);
  BasicBlock* label_for_body_lr_ph = BasicBlock::Create(mod->getContext(), "for.body.lr.ph",func_filter_kernel,0);
  BasicBlock* label_for_body = BasicBlock::Create(mod->getContext(), "for.body",func_filter_kernel,0);
  BasicBlock* label_for_body4_lr_ph = BasicBlock::Create(mod->getContext(), "for.body4.lr.ph",func_filter_kernel,0);
  BasicBlock* label_for_body4 = BasicBlock::Create(mod->getContext(), "for.body4",func_filter_kernel,0);
  BasicBlock* label_for_inc = BasicBlock::Create(mod->getContext(), "for.inc",func_filter_kernel,0);
  BasicBlock* label_for_cond2_for_end_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond2.for.end_crit_edge",func_filter_kernel,0);
  BasicBlock* label_for_end = BasicBlock::Create(mod->getContext(), "for.end",func_filter_kernel,0);
  BasicBlock* label_for_inc16 = BasicBlock::Create(mod->getContext(), "for.inc16",func_filter_kernel,0);
  BasicBlock* label_for_cond_for_end18_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond.for.end18_crit_edge",func_filter_kernel,0);
  BasicBlock* label_for_end18 = BasicBlock::Create(mod->getContext(), "for.end18",func_filter_kernel,0);
  
  // Block entry (label_entry)
  std::vector<Value*> void_18_params;
  void_18_params.push_back(other_19);
  void_18_params.push_back(const_int64_12);
  void_18_params.push_back(other_20);
  void_18_params.push_back(other_21);
  CallInst* void_18 = CallInst::Create(func_llvm_dbg_value, void_18_params, "", label_entry);
  void_18->setCallingConv(CallingConv::C);
  void_18->setTailCall(false);
  AttributeSet void_18_PAL;
  void_18->setAttributes(void_18_PAL);
  
  std::vector<Value*> void_22_params;
  void_22_params.push_back(other_23);
  void_22_params.push_back(const_int64_12);
  void_22_params.push_back(other_24);
  void_22_params.push_back(other_21);
  CallInst* void_22 = CallInst::Create(func_llvm_dbg_value, void_22_params, "", label_entry);
  void_22->setCallingConv(CallingConv::C);
  void_22->setTailCall(false);
  AttributeSet void_22_PAL;
  void_22->setAttributes(void_22_PAL);
  
  std::vector<Value*> void_25_params;
  void_25_params.push_back(other_26);
  void_25_params.push_back(const_int64_12);
  void_25_params.push_back(other_27);
  void_25_params.push_back(other_21);
  CallInst* void_25 = CallInst::Create(func_llvm_dbg_value, void_25_params, "", label_entry);
  void_25->setCallingConv(CallingConv::C);
  void_25->setTailCall(false);
  AttributeSet void_25_PAL;
  void_25->setAttributes(void_25_PAL);
  
  std::vector<Value*> void_28_params;
  void_28_params.push_back(other_29);
  void_28_params.push_back(const_int64_12);
  void_28_params.push_back(other_30);
  void_28_params.push_back(other_21);
  CallInst* void_28 = CallInst::Create(func_llvm_dbg_value, void_28_params, "", label_entry);
  void_28->setCallingConv(CallingConv::C);
  void_28->setTailCall(false);
  AttributeSet void_28_PAL;
  void_28->setAttributes(void_28_PAL);
  
  std::vector<Value*> void_31_params;
  void_31_params.push_back(other_32);
  void_31_params.push_back(const_int64_12);
  void_31_params.push_back(other_33);
  void_31_params.push_back(other_21);
  CallInst* void_31 = CallInst::Create(func_llvm_dbg_value, void_31_params, "", label_entry);
  void_31->setCallingConv(CallingConv::C);
  void_31->setTailCall(false);
  AttributeSet void_31_PAL;
  void_31->setAttributes(void_31_PAL);
  
  std::vector<Value*> void_34_params;
  void_34_params.push_back(other_35);
  void_34_params.push_back(const_int64_12);
  void_34_params.push_back(other_36);
  void_34_params.push_back(other_21);
  CallInst* void_34 = CallInst::Create(func_llvm_dbg_value, void_34_params, "", label_entry);
  void_34->setCallingConv(CallingConv::C);
  void_34->setTailCall(false);
  AttributeSet void_34_PAL;
  void_34->setAttributes(void_34_PAL);
  
  std::vector<Value*> void_37_params;
  void_37_params.push_back(other_38);
  void_37_params.push_back(const_int64_12);
  void_37_params.push_back(other_39);
  void_37_params.push_back(other_21);
  CallInst* void_37 = CallInst::Create(func_llvm_dbg_value, void_37_params, "", label_entry);
  void_37->setCallingConv(CallingConv::C);
  void_37->setTailCall(false);
  AttributeSet void_37_PAL;
  void_37->setAttributes(void_37_PAL);
  
  std::vector<Value*> void_40_params;
  void_40_params.push_back(other_41);
  void_40_params.push_back(const_int64_12);
  void_40_params.push_back(other_42);
  void_40_params.push_back(other_21);
  CallInst* void_40 = CallInst::Create(func_llvm_dbg_value, void_40_params, "", label_entry);
  void_40->setCallingConv(CallingConv::C);
  void_40->setTailCall(false);
  AttributeSet void_40_PAL;
  void_40->setAttributes(void_40_PAL);
  
  BinaryOperator* int32_div = BinaryOperator::Create(Instruction::SDiv, int32_kn, const_int32_13, "div", label_entry);
  std::vector<Value*> void_43_params;
  void_43_params.push_back(other_44);
  void_43_params.push_back(const_int64_12);
  void_43_params.push_back(other_45);
  void_43_params.push_back(other_21);
  CallInst* void_43 = CallInst::Create(func_llvm_dbg_value, void_43_params, "", label_entry);
  void_43->setCallingConv(CallingConv::C);
  void_43->setTailCall(false);
  AttributeSet void_43_PAL;
  void_43->setAttributes(void_43_PAL);
  
  std::vector<Value*> void_46_params;
  void_46_params.push_back(other_47);
  void_46_params.push_back(const_int64_12);
  void_46_params.push_back(other_48);
  void_46_params.push_back(other_21);
  CallInst* void_46 = CallInst::Create(func_llvm_dbg_value, void_46_params, "", label_entry);
  void_46->setCallingConv(CallingConv::C);
  void_46->setTailCall(false);
  AttributeSet void_46_PAL;
  void_46->setAttributes(void_46_PAL);
  
  std::vector<Value*> void_49_params;
  void_49_params.push_back(other_50);
  void_49_params.push_back(const_int64_12);
  void_49_params.push_back(other_51);
  void_49_params.push_back(other_21);
  CallInst* void_49 = CallInst::Create(func_llvm_dbg_value, void_49_params, "", label_entry);
  void_49->setCallingConv(CallingConv::C);
  void_49->setTailCall(false);
  AttributeSet void_49_PAL;
  void_49->setAttributes(void_49_PAL);
  
  BinaryOperator* int32_sub = BinaryOperator::Create(Instruction::Sub, const_int32_14, int32_div, "sub", label_entry);
  std::vector<Value*> void_52_params;
  void_52_params.push_back(other_53);
  void_52_params.push_back(const_int64_12);
  void_52_params.push_back(other_54);
  void_52_params.push_back(other_21);
  CallInst* void_52 = CallInst::Create(func_llvm_dbg_value, void_52_params, "", label_entry);
  void_52->setCallingConv(CallingConv::C);
  void_52->setTailCall(false);
  AttributeSet void_52_PAL;
  void_52->setAttributes(void_52_PAL);
  
  CastInst* int64_55 = new SExtInst(int32_sub, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_56 = new SExtInst(int32_div, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_57 = new SExtInst(int32_sub, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_58 = new SExtInst(int32_div, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_59 = new SExtInst(int32_n, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_60 = new SExtInst(int32_size_x, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_61 = new SExtInst(int32_m, IntegerType::get(mod->getContext(), 64), "", label_entry);
  CastInst* int64_62 = new SExtInst(int32_kn, IntegerType::get(mod->getContext(), 64), "", label_entry);
  ICmpInst* int1_cmp15 = new ICmpInst(*label_entry, ICmpInst::ICMP_SLE, int64_57, int64_58, "cmp15");
  BranchInst::Create(label_for_body_lr_ph, label_for_end18, int1_cmp15, label_entry);
  
  // Block for.body.lr.ph (label_for_body_lr_ph)
  BranchInst::Create(label_for_body, label_for_body_lr_ph);
  
  // Block for.body (label_for_body)
  Argument* fwdref_65 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_018 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.018", label_for_body);
  float_pixel_018->addIncoming(const_float_15, label_for_body_lr_ph);
  float_pixel_018->addIncoming(fwdref_65, label_for_inc16);
  
  Argument* fwdref_66 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv16 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv16", label_for_body);
  int64_indvars_iv16->addIncoming(int64_57, label_for_body_lr_ph);
  int64_indvars_iv16->addIncoming(fwdref_66, label_for_inc16);
  
  std::vector<Value*> void_67_params;
  void_67_params.push_back(other_68);
  void_67_params.push_back(const_int64_12);
  void_67_params.push_back(other_69);
  void_67_params.push_back(other_21);
  CallInst* void_67 = CallInst::Create(func_llvm_dbg_value, void_67_params, "", label_for_body);
  void_67->setCallingConv(CallingConv::C);
  void_67->setTailCall(false);
  AttributeSet void_67_PAL;
  void_67->setAttributes(void_67_PAL);
  
  ICmpInst* int1_cmp33 = new ICmpInst(*label_for_body, ICmpInst::ICMP_SLE, int64_55, int64_56, "cmp33");
  BranchInst::Create(label_for_body4_lr_ph, label_for_end, int1_cmp33, label_for_body);
  
  // Block for.body4.lr.ph (label_for_body4_lr_ph)
  BranchInst::Create(label_for_body4, label_for_body4_lr_ph);
  
  // Block for.body4 (label_for_body4)
  Argument* fwdref_72 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_15 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.15", label_for_body4);
  float_pixel_15->addIncoming(float_pixel_018, label_for_body4_lr_ph);
  float_pixel_15->addIncoming(fwdref_72, label_for_inc);
  
  Argument* fwdref_73 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv4 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv4", label_for_body4);
  int64_indvars_iv4->addIncoming(int64_55, label_for_body4_lr_ph);
  int64_indvars_iv4->addIncoming(fwdref_73, label_for_inc);
  
  BinaryOperator* int64_74 = BinaryOperator::Create(Instruction::Sub, int64_59, int64_indvars_iv16, "", label_for_body4);
  BinaryOperator* int64_75 = BinaryOperator::Create(Instruction::Mul, int64_74, int64_60, "", label_for_body4);
  BinaryOperator* int64_76 = BinaryOperator::Create(Instruction::Add, int64_75, int64_61, "", label_for_body4);
  BinaryOperator* int64_77 = BinaryOperator::Create(Instruction::Sub, int64_76, int64_indvars_iv4, "", label_for_body4);
  GetElementPtrInst* ptr_arrayidx = GetElementPtrInst::Create(ptr_in, int64_77, "arrayidx", label_for_body4);
  LoadInst* int8_78 = new LoadInst(ptr_arrayidx, "", false, label_for_body4);
  int8_78->setAlignment(1);
  CastInst* int32_conv = new ZExtInst(int8_78, IntegerType::get(mod->getContext(), 32), "conv", label_for_body4);
  CastInst* float_conv7 = new SIToFPInst(int32_conv, Type::getFloatTy(mod->getContext()), "conv7", label_for_body4);
  BinaryOperator* int64_79 = BinaryOperator::Create(Instruction::Mul, int64_indvars_iv16, int64_62, "", label_for_body4);
  BinaryOperator* int64_80 = BinaryOperator::Create(Instruction::Sub, const_int64_16, int64_79, "", label_for_body4);
  BinaryOperator* int64_81 = BinaryOperator::Create(Instruction::Add, int64_80, const_int64_16, "", label_for_body4);
  BinaryOperator* int64_82 = BinaryOperator::Create(Instruction::Sub, int64_81, int64_indvars_iv4, "", label_for_body4);
  GetElementPtrInst* ptr_arrayidx13 = GetElementPtrInst::Create(ptr_kernel, int64_82, "arrayidx13", label_for_body4);
  LoadInst* float_83 = new LoadInst(ptr_arrayidx13, "", false, label_for_body4);
  float_83->setAlignment(4);
  BinaryOperator* float_mul14 = BinaryOperator::Create(Instruction::FMul, float_conv7, float_83, "mul14", label_for_body4);
  BinaryOperator* float_add15 = BinaryOperator::Create(Instruction::FAdd, float_pixel_15, float_mul14, "add15", label_for_body4);
  std::vector<Value*> void_84_params;
  void_84_params.push_back(other_85);
  void_84_params.push_back(const_int64_12);
  void_84_params.push_back(other_48);
  void_84_params.push_back(other_21);
  CallInst* void_84 = CallInst::Create(func_llvm_dbg_value, void_84_params, "", label_for_body4);
  void_84->setCallingConv(CallingConv::C);
  void_84->setTailCall(false);
  AttributeSet void_84_PAL;
  void_84->setAttributes(void_84_PAL);
  
  BranchInst::Create(label_for_inc, label_for_body4);
  
  // Block for.inc (label_for_inc)
  BinaryOperator* int64_indvars_iv_next = BinaryOperator::Create(Instruction::Add, int64_indvars_iv4, const_int64_16, "indvars.iv.next", label_for_inc);
  std::vector<Value*> void_87_params;
  void_87_params.push_back(other_68);
  void_87_params.push_back(const_int64_12);
  void_87_params.push_back(other_69);
  void_87_params.push_back(other_21);
  CallInst* void_87 = CallInst::Create(func_llvm_dbg_value, void_87_params, "", label_for_inc);
  void_87->setCallingConv(CallingConv::C);
  void_87->setTailCall(false);
  AttributeSet void_87_PAL;
  void_87->setAttributes(void_87_PAL);
  
  ICmpInst* int1_cmp3 = new ICmpInst(*label_for_inc, ICmpInst::ICMP_SLE, int64_indvars_iv_next, int64_56, "cmp3");
  BranchInst::Create(label_for_body4, label_for_cond2_for_end_crit_edge, int1_cmp3, label_for_inc);
  
  // Block for.cond2.for.end_crit_edge (label_for_cond2_for_end_crit_edge)
  PHINode* float_split = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split", label_for_cond2_for_end_crit_edge);
  float_split->addIncoming(float_add15, label_for_inc);
  
  BranchInst::Create(label_for_end, label_for_cond2_for_end_crit_edge);
  
  // Block for.end (label_for_end)
  PHINode* int64_indvars_iv17 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv17", label_for_end);
  int64_indvars_iv17->addIncoming(int64_indvars_iv16, label_for_cond2_for_end_crit_edge);
  int64_indvars_iv17->addIncoming(int64_indvars_iv16, label_for_body);
  
  PHINode* float_pixel_1_lcssa = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.1.lcssa", label_for_end);
  float_pixel_1_lcssa->addIncoming(float_split, label_for_cond2_for_end_crit_edge);
  float_pixel_1_lcssa->addIncoming(float_pixel_018, label_for_body);
  
  BranchInst::Create(label_for_inc16, label_for_end);
  
  // Block for.inc16 (label_for_inc16)
  BinaryOperator* int64_indvars_iv_next6 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv17, const_int64_16, "indvars.iv.next6", label_for_inc16);
  std::vector<Value*> void_91_params;
  void_91_params.push_back(other_68);
  void_91_params.push_back(const_int64_12);
  void_91_params.push_back(other_54);
  void_91_params.push_back(other_21);
  CallInst* void_91 = CallInst::Create(func_llvm_dbg_value, void_91_params, "", label_for_inc16);
  void_91->setCallingConv(CallingConv::C);
  void_91->setTailCall(false);
  AttributeSet void_91_PAL;
  void_91->setAttributes(void_91_PAL);
  
  ICmpInst* int1_cmp = new ICmpInst(*label_for_inc16, ICmpInst::ICMP_SLE, int64_indvars_iv_next6, int64_58, "cmp");
  BranchInst::Create(label_for_body, label_for_cond_for_end18_crit_edge, int1_cmp, label_for_inc16);
  
  // Block for.cond.for.end18_crit_edge (label_for_cond_for_end18_crit_edge)
  PHINode* float_split19 = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split19", label_for_cond_for_end18_crit_edge);
  float_split19->addIncoming(float_pixel_1_lcssa, label_for_inc16);
  
  BranchInst::Create(label_for_end18, label_for_cond_for_end18_crit_edge);
  
  // Block for.end18 (label_for_end18)
  PHINode* float_pixel_0_lcssa = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.0.lcssa", label_for_end18);
  float_pixel_0_lcssa->addIncoming(float_split19, label_for_cond_for_end18_crit_edge);
  float_pixel_0_lcssa->addIncoming(const_float_15, label_entry);
  
  CastInst* int8_conv19 = new FPToUIInst(float_pixel_0_lcssa, IntegerType::get(mod->getContext(), 8), "conv19", label_for_end18);
  BinaryOperator* int32_mul20 = BinaryOperator::Create(Instruction::Mul, int32_n, int32_size_x, "mul20", label_for_end18);
  BinaryOperator* int32_add21 = BinaryOperator::Create(Instruction::Add, int32_mul20, int32_m, "add21", label_for_end18);
  CastInst* int64_idxprom22 = new SExtInst(int32_add21, IntegerType::get(mod->getContext(), 64), "idxprom22", label_for_end18);
  GetElementPtrInst* ptr_arrayidx23 = GetElementPtrInst::Create(ptr_out, int64_idxprom22, "arrayidx23", label_for_end18);
  StoreInst* void_94 = new StoreInst(int8_conv19, ptr_arrayidx23, false, label_for_end18);
  void_94->setAlignment(1);
  ReturnInst::Create(mod->getContext(), label_for_end18);
  
  // Resolve Forward References
  fwdref_72->replaceAllUsesWith(float_add15); delete fwdref_72;
  fwdref_73->replaceAllUsesWith(int64_indvars_iv_next); delete fwdref_73;
  fwdref_65->replaceAllUsesWith(float_pixel_1_lcssa); delete fwdref_65;
  fwdref_66->replaceAllUsesWith(int64_indvars_iv_next6); delete fwdref_66;
  
 }
 
 // Function: filter_kernel_2d (func_filter_kernel_2d)
 {
  Function::arg_iterator args = func_filter_kernel_2d->arg_begin();
  Value* ptr_in_96 = args++;
  ptr_in_96->setName("in");
  Value* ptr_out_97 = args++;
  ptr_out_97->setName("out");
  Value* ptr_kernel_98 = args++;
  ptr_kernel_98->setName("kernel");
  Value* int32_kn_99 = args++;
  int32_kn_99->setName("kn");
  Value* int32_x = args++;
  int32_x->setName("x");
  Value* int32_y = args++;
  int32_y->setName("y");
  
  BasicBlock* label_entry_100 = BasicBlock::Create(mod->getContext(), "entry",func_filter_kernel_2d,0);
  BasicBlock* label_for_body_lr_ph_101 = BasicBlock::Create(mod->getContext(), "for.body.lr.ph",func_filter_kernel_2d,0);
  BasicBlock* label_for_body_102 = BasicBlock::Create(mod->getContext(), "for.body",func_filter_kernel_2d,0);
  BasicBlock* label_for_body4_lr_ph_103 = BasicBlock::Create(mod->getContext(), "for.body4.lr.ph",func_filter_kernel_2d,0);
  BasicBlock* label_for_body4_104 = BasicBlock::Create(mod->getContext(), "for.body4",func_filter_kernel_2d,0);
  BasicBlock* label_for_inc_105 = BasicBlock::Create(mod->getContext(), "for.inc",func_filter_kernel_2d,0);
  BasicBlock* label_for_cond2_for_end_crit_edge_106 = BasicBlock::Create(mod->getContext(), "for.cond2.for.end_crit_edge",func_filter_kernel_2d,0);
  BasicBlock* label_for_end_107 = BasicBlock::Create(mod->getContext(), "for.end",func_filter_kernel_2d,0);
  BasicBlock* label_for_inc13 = BasicBlock::Create(mod->getContext(), "for.inc13",func_filter_kernel_2d,0);
  BasicBlock* label_for_cond_for_end15_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond.for.end15_crit_edge",func_filter_kernel_2d,0);
  BasicBlock* label_for_end15 = BasicBlock::Create(mod->getContext(), "for.end15",func_filter_kernel_2d,0);
  
  // Block entry (label_entry_100)
  std::vector<Value*> void_108_params;
  void_108_params.push_back(other_109);
  void_108_params.push_back(const_int64_12);
  void_108_params.push_back(other_110);
  void_108_params.push_back(other_21);
  CallInst* void_108 = CallInst::Create(func_llvm_dbg_value, void_108_params, "", label_entry_100);
  void_108->setCallingConv(CallingConv::C);
  void_108->setTailCall(false);
  AttributeSet void_108_PAL;
  void_108->setAttributes(void_108_PAL);
  
  std::vector<Value*> void_111_params;
  void_111_params.push_back(other_112);
  void_111_params.push_back(const_int64_12);
  void_111_params.push_back(other_113);
  void_111_params.push_back(other_21);
  CallInst* void_111 = CallInst::Create(func_llvm_dbg_value, void_111_params, "", label_entry_100);
  void_111->setCallingConv(CallingConv::C);
  void_111->setTailCall(false);
  AttributeSet void_111_PAL;
  void_111->setAttributes(void_111_PAL);
  
  std::vector<Value*> void_114_params;
  void_114_params.push_back(other_115);
  void_114_params.push_back(const_int64_12);
  void_114_params.push_back(other_116);
  void_114_params.push_back(other_21);
  CallInst* void_114 = CallInst::Create(func_llvm_dbg_value, void_114_params, "", label_entry_100);
  void_114->setCallingConv(CallingConv::C);
  void_114->setTailCall(false);
  AttributeSet void_114_PAL;
  void_114->setAttributes(void_114_PAL);
  
  std::vector<Value*> void_117_params;
  void_117_params.push_back(other_118);
  void_117_params.push_back(const_int64_12);
  void_117_params.push_back(other_119);
  void_117_params.push_back(other_21);
  CallInst* void_117 = CallInst::Create(func_llvm_dbg_value, void_117_params, "", label_entry_100);
  void_117->setCallingConv(CallingConv::C);
  void_117->setTailCall(false);
  AttributeSet void_117_PAL;
  void_117->setAttributes(void_117_PAL);
  
  std::vector<Value*> void_120_params;
  void_120_params.push_back(other_121);
  void_120_params.push_back(const_int64_12);
  void_120_params.push_back(other_122);
  void_120_params.push_back(other_21);
  CallInst* void_120 = CallInst::Create(func_llvm_dbg_value, void_120_params, "", label_entry_100);
  void_120->setCallingConv(CallingConv::C);
  void_120->setTailCall(false);
  AttributeSet void_120_PAL;
  void_120->setAttributes(void_120_PAL);
  
  std::vector<Value*> void_123_params;
  void_123_params.push_back(other_124);
  void_123_params.push_back(const_int64_12);
  void_123_params.push_back(other_125);
  void_123_params.push_back(other_21);
  CallInst* void_123 = CallInst::Create(func_llvm_dbg_value, void_123_params, "", label_entry_100);
  void_123->setCallingConv(CallingConv::C);
  void_123->setTailCall(false);
  AttributeSet void_123_PAL;
  void_123->setAttributes(void_123_PAL);
  
  BinaryOperator* int32_div_126 = BinaryOperator::Create(Instruction::SDiv, int32_kn_99, const_int32_13, "div", label_entry_100);
  std::vector<Value*> void_127_params;
  void_127_params.push_back(other_128);
  void_127_params.push_back(const_int64_12);
  void_127_params.push_back(other_129);
  void_127_params.push_back(other_21);
  CallInst* void_127 = CallInst::Create(func_llvm_dbg_value, void_127_params, "", label_entry_100);
  void_127->setCallingConv(CallingConv::C);
  void_127->setTailCall(false);
  AttributeSet void_127_PAL;
  void_127->setAttributes(void_127_PAL);
  
  std::vector<Value*> void_130_params;
  void_130_params.push_back(other_47);
  void_130_params.push_back(const_int64_12);
  void_130_params.push_back(other_131);
  void_130_params.push_back(other_21);
  CallInst* void_130 = CallInst::Create(func_llvm_dbg_value, void_130_params, "", label_entry_100);
  void_130->setCallingConv(CallingConv::C);
  void_130->setTailCall(false);
  AttributeSet void_130_PAL;
  void_130->setAttributes(void_130_PAL);
  
  std::vector<Value*> void_132_params;
  void_132_params.push_back(other_50);
  void_132_params.push_back(const_int64_12);
  void_132_params.push_back(other_133);
  void_132_params.push_back(other_21);
  CallInst* void_132 = CallInst::Create(func_llvm_dbg_value, void_132_params, "", label_entry_100);
  void_132->setCallingConv(CallingConv::C);
  void_132->setTailCall(false);
  AttributeSet void_132_PAL;
  void_132->setAttributes(void_132_PAL);
  
  BinaryOperator* int32_sub_134 = BinaryOperator::Create(Instruction::Sub, const_int32_14, int32_div_126, "sub", label_entry_100);
  std::vector<Value*> void_135_params;
  void_135_params.push_back(other_136);
  void_135_params.push_back(const_int64_12);
  void_135_params.push_back(other_137);
  void_135_params.push_back(other_21);
  CallInst* void_135 = CallInst::Create(func_llvm_dbg_value, void_135_params, "", label_entry_100);
  void_135->setCallingConv(CallingConv::C);
  void_135->setTailCall(false);
  AttributeSet void_135_PAL;
  void_135->setAttributes(void_135_PAL);
  
  CastInst* int64_138 = new SExtInst(int32_sub_134, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  CastInst* int64_139 = new SExtInst(int32_div_126, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  CastInst* int64_140 = new SExtInst(int32_x, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  CastInst* int64_141 = new SExtInst(int32_sub_134, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  CastInst* int64_142 = new SExtInst(int32_div_126, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  CastInst* int64_143 = new SExtInst(int32_y, IntegerType::get(mod->getContext(), 64), "", label_entry_100);
  ICmpInst* int1_cmp11 = new ICmpInst(*label_entry_100, ICmpInst::ICMP_SLE, int64_141, int64_142, "cmp11");
  BranchInst::Create(label_for_body_lr_ph_101, label_for_end15, int1_cmp11, label_entry_100);
  
  // Block for.body.lr.ph (label_for_body_lr_ph_101)
  BranchInst::Create(label_for_body_102, label_for_body_lr_ph_101);
  
  // Block for.body (label_for_body_102)
  Argument* fwdref_146 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_c_015 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "c.015", label_for_body_102);
  int32_c_015->addIncoming(const_int32_14, label_for_body_lr_ph_101);
  int32_c_015->addIncoming(fwdref_146, label_for_inc13);
  
  Argument* fwdref_147 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_014 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.014", label_for_body_102);
  float_pixel_014->addIncoming(const_float_15, label_for_body_lr_ph_101);
  float_pixel_014->addIncoming(fwdref_147, label_for_inc13);
  
  Argument* fwdref_148 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv12 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv12", label_for_body_102);
  int64_indvars_iv12->addIncoming(int64_141, label_for_body_lr_ph_101);
  int64_indvars_iv12->addIncoming(fwdref_148, label_for_inc13);
  
  std::vector<Value*> void_149_params;
  void_149_params.push_back(other_68);
  void_149_params.push_back(const_int64_12);
  void_149_params.push_back(other_150);
  void_149_params.push_back(other_21);
  CallInst* void_149 = CallInst::Create(func_llvm_dbg_value, void_149_params, "", label_for_body_102);
  void_149->setCallingConv(CallingConv::C);
  void_149->setTailCall(false);
  AttributeSet void_149_PAL;
  void_149->setAttributes(void_149_PAL);
  
  CastInst* int64_151 = new SExtInst(int32_c_015, IntegerType::get(mod->getContext(), 64), "", label_for_body_102);
  ICmpInst* int1_cmp34 = new ICmpInst(*label_for_body_102, ICmpInst::ICMP_SLE, int64_138, int64_139, "cmp34");
  BranchInst::Create(label_for_body4_lr_ph_103, label_for_end_107, int1_cmp34, label_for_body_102);
  
  // Block for.body4.lr.ph (label_for_body4_lr_ph_103)
  BranchInst::Create(label_for_body4_104, label_for_body4_lr_ph_103);
  
  // Block for.body4 (label_for_body4_104)
  Argument* fwdref_154 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_17 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.17", label_for_body4_104);
  float_pixel_17->addIncoming(float_pixel_014, label_for_body4_lr_ph_103);
  float_pixel_17->addIncoming(fwdref_154, label_for_inc_105);
  
  Argument* fwdref_155 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv6 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv6", label_for_body4_104);
  int64_indvars_iv6->addIncoming(int64_151, label_for_body4_lr_ph_103);
  int64_indvars_iv6->addIncoming(fwdref_155, label_for_inc_105);
  
  Argument* fwdref_156 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv15 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv15", label_for_body4_104);
  int64_indvars_iv15->addIncoming(int64_138, label_for_body4_lr_ph_103);
  int64_indvars_iv15->addIncoming(fwdref_156, label_for_inc_105);
  
  BinaryOperator* int64_157 = BinaryOperator::Create(Instruction::Add, int64_140, int64_indvars_iv15, "", label_for_body4_104);
  BinaryOperator* int64_158 = BinaryOperator::Create(Instruction::Add, int64_143, int64_indvars_iv12, "", label_for_body4_104);
  GetElementPtrInst* ptr_arrayidx_159 = GetElementPtrInst::Create(ptr_in_96, int64_158, "arrayidx", label_for_body4_104);
  LoadInst* ptr_160 = new LoadInst(ptr_arrayidx_159, "", false, label_for_body4_104);
  ptr_160->setAlignment(8);
  GetElementPtrInst* ptr_arrayidx7 = GetElementPtrInst::Create(ptr_160, int64_157, "arrayidx7", label_for_body4_104);
  LoadInst* int8_161 = new LoadInst(ptr_arrayidx7, "", false, label_for_body4_104);
  int8_161->setAlignment(1);
  CastInst* int32_conv_162 = new ZExtInst(int8_161, IntegerType::get(mod->getContext(), 32), "conv", label_for_body4_104);
  CastInst* float_conv8 = new SIToFPInst(int32_conv_162, Type::getFloatTy(mod->getContext()), "conv8", label_for_body4_104);
  BinaryOperator* int64_indvars_iv_next_163 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv6, const_int64_16, "indvars.iv.next", label_for_body4_104);
  std::vector<Value*> void_164_params;
  void_164_params.push_back(other_68);
  void_164_params.push_back(const_int64_12);
  void_164_params.push_back(other_133);
  void_164_params.push_back(other_21);
  CallInst* void_164 = CallInst::Create(func_llvm_dbg_value, void_164_params, "", label_for_body4_104);
  void_164->setCallingConv(CallingConv::C);
  void_164->setTailCall(false);
  AttributeSet void_164_PAL;
  void_164->setAttributes(void_164_PAL);
  
  GetElementPtrInst* ptr_arrayidx10 = GetElementPtrInst::Create(ptr_kernel_98, int64_indvars_iv6, "arrayidx10", label_for_body4_104);
  LoadInst* float_165 = new LoadInst(ptr_arrayidx10, "", false, label_for_body4_104);
  float_165->setAlignment(4);
  BinaryOperator* float_mul = BinaryOperator::Create(Instruction::FMul, float_conv8, float_165, "mul", label_for_body4_104);
  BinaryOperator* float_add11 = BinaryOperator::Create(Instruction::FAdd, float_pixel_17, float_mul, "add11", label_for_body4_104);
  std::vector<Value*> void_166_params;
  void_166_params.push_back(other_167);
  void_166_params.push_back(const_int64_12);
  void_166_params.push_back(other_131);
  void_166_params.push_back(other_21);
  CallInst* void_166 = CallInst::Create(func_llvm_dbg_value, void_166_params, "", label_for_body4_104);
  void_166->setCallingConv(CallingConv::C);
  void_166->setTailCall(false);
  AttributeSet void_166_PAL;
  void_166->setAttributes(void_166_PAL);
  
  BranchInst::Create(label_for_inc_105, label_for_body4_104);
  
  // Block for.inc (label_for_inc_105)
  BinaryOperator* int64_indvars_iv_next2 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv15, const_int64_16, "indvars.iv.next2", label_for_inc_105);
  std::vector<Value*> void_169_params;
  void_169_params.push_back(other_68);
  void_169_params.push_back(const_int64_12);
  void_169_params.push_back(other_150);
  void_169_params.push_back(other_21);
  CallInst* void_169 = CallInst::Create(func_llvm_dbg_value, void_169_params, "", label_for_inc_105);
  void_169->setCallingConv(CallingConv::C);
  void_169->setTailCall(false);
  AttributeSet void_169_PAL;
  void_169->setAttributes(void_169_PAL);
  
  ICmpInst* int1_cmp3_170 = new ICmpInst(*label_for_inc_105, ICmpInst::ICMP_SLE, int64_indvars_iv_next2, int64_139, "cmp3");
  BranchInst::Create(label_for_body4_104, label_for_cond2_for_end_crit_edge_106, int1_cmp3_170, label_for_inc_105);
  
  // Block for.cond2.for.end_crit_edge (label_for_cond2_for_end_crit_edge_106)
  PHINode* int64_split = PHINode::Create(IntegerType::get(mod->getContext(), 64), 1, "split", label_for_cond2_for_end_crit_edge_106);
  int64_split->addIncoming(int64_indvars_iv_next_163, label_for_inc_105);
  
  PHINode* float_split8 = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split8", label_for_cond2_for_end_crit_edge_106);
  float_split8->addIncoming(float_add11, label_for_inc_105);
  
  BranchInst::Create(label_for_end_107, label_for_cond2_for_end_crit_edge_106);
  
  // Block for.end (label_for_end_107)
  PHINode* int64_indvars_iv13 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv13", label_for_end_107);
  int64_indvars_iv13->addIncoming(int64_indvars_iv12, label_for_cond2_for_end_crit_edge_106);
  int64_indvars_iv13->addIncoming(int64_indvars_iv12, label_for_body_102);
  
  PHINode* int64_c_1_lcssa_wide = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "c.1.lcssa.wide", label_for_end_107);
  int64_c_1_lcssa_wide->addIncoming(int64_split, label_for_cond2_for_end_crit_edge_106);
  int64_c_1_lcssa_wide->addIncoming(int64_151, label_for_body_102);
  
  PHINode* float_pixel_1_lcssa_173 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.1.lcssa", label_for_end_107);
  float_pixel_1_lcssa_173->addIncoming(float_split8, label_for_cond2_for_end_crit_edge_106);
  float_pixel_1_lcssa_173->addIncoming(float_pixel_014, label_for_body_102);
  
  CastInst* int32_174 = new TruncInst(int64_c_1_lcssa_wide, IntegerType::get(mod->getContext(), 32), "", label_for_end_107);
  BranchInst::Create(label_for_inc13, label_for_end_107);
  
  // Block for.inc13 (label_for_inc13)
  BinaryOperator* int64_indvars_iv_next9 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv13, const_int64_16, "indvars.iv.next9", label_for_inc13);
  std::vector<Value*> void_176_params;
  void_176_params.push_back(other_68);
  void_176_params.push_back(const_int64_12);
  void_176_params.push_back(other_137);
  void_176_params.push_back(other_21);
  CallInst* void_176 = CallInst::Create(func_llvm_dbg_value, void_176_params, "", label_for_inc13);
  void_176->setCallingConv(CallingConv::C);
  void_176->setTailCall(false);
  AttributeSet void_176_PAL;
  void_176->setAttributes(void_176_PAL);
  
  ICmpInst* int1_cmp_177 = new ICmpInst(*label_for_inc13, ICmpInst::ICMP_SLE, int64_indvars_iv_next9, int64_142, "cmp");
  BranchInst::Create(label_for_body_102, label_for_cond_for_end15_crit_edge, int1_cmp_177, label_for_inc13);
  
  // Block for.cond.for.end15_crit_edge (label_for_cond_for_end15_crit_edge)
  PHINode* float_split16 = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split16", label_for_cond_for_end15_crit_edge);
  float_split16->addIncoming(float_pixel_1_lcssa_173, label_for_inc13);
  
  BranchInst::Create(label_for_end15, label_for_cond_for_end15_crit_edge);
  
  // Block for.end15 (label_for_end15)
  PHINode* float_pixel_0_lcssa_180 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.0.lcssa", label_for_end15);
  float_pixel_0_lcssa_180->addIncoming(float_split16, label_for_cond_for_end15_crit_edge);
  float_pixel_0_lcssa_180->addIncoming(const_float_15, label_entry_100);
  
  CastInst* int8_conv16 = new FPToUIInst(float_pixel_0_lcssa_180, IntegerType::get(mod->getContext(), 8), "conv16", label_for_end15);
  CastInst* int64_idxprom17 = new SExtInst(int32_x, IntegerType::get(mod->getContext(), 64), "idxprom17", label_for_end15);
  CastInst* int64_idxprom18 = new SExtInst(int32_y, IntegerType::get(mod->getContext(), 64), "idxprom18", label_for_end15);
  GetElementPtrInst* ptr_arrayidx19 = GetElementPtrInst::Create(ptr_out_97, int64_idxprom18, "arrayidx19", label_for_end15);
  LoadInst* ptr_181 = new LoadInst(ptr_arrayidx19, "", false, label_for_end15);
  ptr_181->setAlignment(8);
  GetElementPtrInst* ptr_arrayidx20 = GetElementPtrInst::Create(ptr_181, int64_idxprom17, "arrayidx20", label_for_end15);
  StoreInst* void_182 = new StoreInst(int8_conv16, ptr_arrayidx20, false, label_for_end15);
  void_182->setAlignment(1);
  ReturnInst::Create(mod->getContext(), label_for_end15);
  
  // Resolve Forward References
  fwdref_156->replaceAllUsesWith(int64_indvars_iv_next2); delete fwdref_156;
  fwdref_148->replaceAllUsesWith(int64_indvars_iv_next9); delete fwdref_148;
  fwdref_155->replaceAllUsesWith(int64_indvars_iv_next_163); delete fwdref_155;
  fwdref_154->replaceAllUsesWith(float_add11); delete fwdref_154;
  fwdref_147->replaceAllUsesWith(float_pixel_1_lcssa_173); delete fwdref_147;
  fwdref_146->replaceAllUsesWith(int32_174); delete fwdref_146;
  
 }
 
 // Function: convolve_arr_linear (func_convolve_arr_linear)
 {
  Function::arg_iterator args = func_convolve_arr_linear->arg_begin();
  Value* ptr_in_184 = args++;
  ptr_in_184->setName("in");
  Value* ptr_out_185 = args++;
  ptr_out_185->setName("out");
  Value* ptr_kernel_186 = args++;
  ptr_kernel_186->setName("kernel");
  Value* int32_kn_187 = args++;
  int32_kn_187->setName("kn");
  Value* int32_dim_x = args++;
  int32_dim_x->setName("dim_x");
  Value* int32_dim_y = args++;
  int32_dim_y->setName("dim_y");
  
  BasicBlock* label_entry_188 = BasicBlock::Create(mod->getContext(), "entry",func_convolve_arr_linear,0);
  BasicBlock* label_for_body_lr_ph_189 = BasicBlock::Create(mod->getContext(), "for.body.lr.ph",func_convolve_arr_linear,0);
  BasicBlock* label_for_body_190 = BasicBlock::Create(mod->getContext(), "for.body",func_convolve_arr_linear,0);
  BasicBlock* label_for_body4_lr_ph_191 = BasicBlock::Create(mod->getContext(), "for.body4.lr.ph",func_convolve_arr_linear,0);
  BasicBlock* label_for_body4_192 = BasicBlock::Create(mod->getContext(), "for.body4",func_convolve_arr_linear,0);
  BasicBlock* label_for_inc_193 = BasicBlock::Create(mod->getContext(), "for.inc",func_convolve_arr_linear,0);
  BasicBlock* label_for_cond1_for_end_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond1.for.end_crit_edge",func_convolve_arr_linear,0);
  BasicBlock* label_for_end_194 = BasicBlock::Create(mod->getContext(), "for.end",func_convolve_arr_linear,0);
  BasicBlock* label_for_inc5 = BasicBlock::Create(mod->getContext(), "for.inc5",func_convolve_arr_linear,0);
  BasicBlock* label_for_cond_for_end7_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond.for.end7_crit_edge",func_convolve_arr_linear,0);
  BasicBlock* label_for_end7 = BasicBlock::Create(mod->getContext(), "for.end7",func_convolve_arr_linear,0);
  
  // Block entry (label_entry_188)
  std::vector<Value*> void_195_params;
  void_195_params.push_back(other_196);
  void_195_params.push_back(const_int64_12);
  void_195_params.push_back(other_197);
  void_195_params.push_back(other_21);
  CallInst* void_195 = CallInst::Create(func_llvm_dbg_value, void_195_params, "", label_entry_188);
  void_195->setCallingConv(CallingConv::C);
  void_195->setTailCall(false);
  AttributeSet void_195_PAL;
  void_195->setAttributes(void_195_PAL);
  
  std::vector<Value*> void_198_params;
  void_198_params.push_back(other_199);
  void_198_params.push_back(const_int64_12);
  void_198_params.push_back(other_200);
  void_198_params.push_back(other_21);
  CallInst* void_198 = CallInst::Create(func_llvm_dbg_value, void_198_params, "", label_entry_188);
  void_198->setCallingConv(CallingConv::C);
  void_198->setTailCall(false);
  AttributeSet void_198_PAL;
  void_198->setAttributes(void_198_PAL);
  
  std::vector<Value*> void_201_params;
  void_201_params.push_back(other_202);
  void_201_params.push_back(const_int64_12);
  void_201_params.push_back(other_203);
  void_201_params.push_back(other_21);
  CallInst* void_201 = CallInst::Create(func_llvm_dbg_value, void_201_params, "", label_entry_188);
  void_201->setCallingConv(CallingConv::C);
  void_201->setTailCall(false);
  AttributeSet void_201_PAL;
  void_201->setAttributes(void_201_PAL);
  
  std::vector<Value*> void_204_params;
  void_204_params.push_back(other_205);
  void_204_params.push_back(const_int64_12);
  void_204_params.push_back(other_206);
  void_204_params.push_back(other_21);
  CallInst* void_204 = CallInst::Create(func_llvm_dbg_value, void_204_params, "", label_entry_188);
  void_204->setCallingConv(CallingConv::C);
  void_204->setTailCall(false);
  AttributeSet void_204_PAL;
  void_204->setAttributes(void_204_PAL);
  
  std::vector<Value*> void_207_params;
  void_207_params.push_back(other_208);
  void_207_params.push_back(const_int64_12);
  void_207_params.push_back(other_209);
  void_207_params.push_back(other_21);
  CallInst* void_207 = CallInst::Create(func_llvm_dbg_value, void_207_params, "", label_entry_188);
  void_207->setCallingConv(CallingConv::C);
  void_207->setTailCall(false);
  AttributeSet void_207_PAL;
  void_207->setAttributes(void_207_PAL);
  
  std::vector<Value*> void_210_params;
  void_210_params.push_back(other_211);
  void_210_params.push_back(const_int64_12);
  void_210_params.push_back(other_212);
  void_210_params.push_back(other_21);
  CallInst* void_210 = CallInst::Create(func_llvm_dbg_value, void_210_params, "", label_entry_188);
  void_210->setCallingConv(CallingConv::C);
  void_210->setTailCall(false);
  AttributeSet void_210_PAL;
  void_210->setAttributes(void_210_PAL);
  
  BinaryOperator* int32_div_213 = BinaryOperator::Create(Instruction::SDiv, int32_kn_187, const_int32_13, "div", label_entry_188);
  std::vector<Value*> void_214_params;
  void_214_params.push_back(other_215);
  void_214_params.push_back(const_int64_12);
  void_214_params.push_back(other_216);
  void_214_params.push_back(other_21);
  CallInst* void_214 = CallInst::Create(func_llvm_dbg_value, void_214_params, "", label_entry_188);
  void_214->setCallingConv(CallingConv::C);
  void_214->setTailCall(false);
  AttributeSet void_214_PAL;
  void_214->setAttributes(void_214_PAL);
  
  std::vector<Value*> void_217_params;
  void_217_params.push_back(other_215);
  void_217_params.push_back(const_int64_12);
  void_217_params.push_back(other_218);
  void_217_params.push_back(other_21);
  CallInst* void_217 = CallInst::Create(func_llvm_dbg_value, void_217_params, "", label_entry_188);
  void_217->setCallingConv(CallingConv::C);
  void_217->setTailCall(false);
  AttributeSet void_217_PAL;
  void_217->setAttributes(void_217_PAL);
  
  BinaryOperator* int32_sub_219 = BinaryOperator::Create(Instruction::Sub, int32_dim_x, int32_div_213, "sub", label_entry_188);
  ICmpInst* int1_cmp4 = new ICmpInst(*label_entry_188, ICmpInst::ICMP_SLT, int32_div_213, int32_sub_219, "cmp4");
  BranchInst::Create(label_for_body_lr_ph_189, label_for_end7, int1_cmp4, label_entry_188);
  
  // Block for.body.lr.ph (label_for_body_lr_ph_189)
  BranchInst::Create(label_for_body_190, label_for_body_lr_ph_189);
  
  // Block for.body (label_for_body_190)
  Argument* fwdref_222 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_m_05 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "m.05", label_for_body_190);
  int32_m_05->addIncoming(int32_div_213, label_for_body_lr_ph_189);
  int32_m_05->addIncoming(fwdref_222, label_for_inc5);
  
  std::vector<Value*> void_223_params;
  void_223_params.push_back(other_215);
  void_223_params.push_back(const_int64_12);
  void_223_params.push_back(other_224);
  void_223_params.push_back(other_21);
  CallInst* void_223 = CallInst::Create(func_llvm_dbg_value, void_223_params, "", label_for_body_190);
  void_223->setCallingConv(CallingConv::C);
  void_223->setTailCall(false);
  AttributeSet void_223_PAL;
  void_223->setAttributes(void_223_PAL);
  
  BinaryOperator* int32_sub2 = BinaryOperator::Create(Instruction::Sub, int32_dim_y, int32_div_213, "sub2", label_for_body_190);
  ICmpInst* int1_cmp31 = new ICmpInst(*label_for_body_190, ICmpInst::ICMP_SLT, int32_div_213, int32_sub2, "cmp31");
  BranchInst::Create(label_for_body4_lr_ph_191, label_for_end_194, int1_cmp31, label_for_body_190);
  
  // Block for.body4.lr.ph (label_for_body4_lr_ph_191)
  BranchInst::Create(label_for_body4_192, label_for_body4_lr_ph_191);
  
  // Block for.body4 (label_for_body4_192)
  Argument* fwdref_227 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_n_02 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "n.02", label_for_body4_192);
  int32_n_02->addIncoming(int32_div_213, label_for_body4_lr_ph_191);
  int32_n_02->addIncoming(fwdref_227, label_for_inc_193);
  
  std::vector<Value*> void_228_params;
  void_228_params.push_back(ptr_in_184);
  void_228_params.push_back(ptr_out_185);
  void_228_params.push_back(ptr_kernel_186);
  void_228_params.push_back(int32_kn_187);
  void_228_params.push_back(int32_m_05);
  void_228_params.push_back(int32_n_02);
  void_228_params.push_back(int32_dim_x);
  void_228_params.push_back(int32_dim_y);
  CallInst* void_228 = CallInst::Create(func_filter_kernel, void_228_params, "", label_for_body4_192);
  void_228->setCallingConv(CallingConv::C);
  void_228->setTailCall(false);
  AttributeSet void_228_PAL;
  void_228->setAttributes(void_228_PAL);
  
  BranchInst::Create(label_for_inc_193, label_for_body4_192);
  
  // Block for.inc (label_for_inc_193)
  BinaryOperator* int32_inc = BinaryOperator::Create(Instruction::Add, int32_n_02, const_int32_17, "inc", label_for_inc_193);
  std::vector<Value*> void_230_params;
  void_230_params.push_back(other_231);
  void_230_params.push_back(const_int64_12);
  void_230_params.push_back(other_224);
  void_230_params.push_back(other_21);
  CallInst* void_230 = CallInst::Create(func_llvm_dbg_value, void_230_params, "", label_for_inc_193);
  void_230->setCallingConv(CallingConv::C);
  void_230->setTailCall(false);
  AttributeSet void_230_PAL;
  void_230->setAttributes(void_230_PAL);
  
  ICmpInst* int1_cmp3_232 = new ICmpInst(*label_for_inc_193, ICmpInst::ICMP_SLT, int32_inc, int32_sub2, "cmp3");
  BranchInst::Create(label_for_body4_192, label_for_cond1_for_end_crit_edge, int1_cmp3_232, label_for_inc_193);
  
  // Block for.cond1.for.end_crit_edge (label_for_cond1_for_end_crit_edge)
  BranchInst::Create(label_for_end_194, label_for_cond1_for_end_crit_edge);
  
  // Block for.end (label_for_end_194)
  BranchInst::Create(label_for_inc5, label_for_end_194);
  
  // Block for.inc5 (label_for_inc5)
  BinaryOperator* int32_inc6 = BinaryOperator::Create(Instruction::Add, int32_m_05, const_int32_17, "inc6", label_for_inc5);
  std::vector<Value*> void_236_params;
  void_236_params.push_back(other_237);
  void_236_params.push_back(const_int64_12);
  void_236_params.push_back(other_218);
  void_236_params.push_back(other_21);
  CallInst* void_236 = CallInst::Create(func_llvm_dbg_value, void_236_params, "", label_for_inc5);
  void_236->setCallingConv(CallingConv::C);
  void_236->setTailCall(false);
  AttributeSet void_236_PAL;
  void_236->setAttributes(void_236_PAL);
  
  ICmpInst* int1_cmp_238 = new ICmpInst(*label_for_inc5, ICmpInst::ICMP_SLT, int32_inc6, int32_sub_219, "cmp");
  BranchInst::Create(label_for_body_190, label_for_cond_for_end7_crit_edge, int1_cmp_238, label_for_inc5);
  
  // Block for.cond.for.end7_crit_edge (label_for_cond_for_end7_crit_edge)
  BranchInst::Create(label_for_end7, label_for_cond_for_end7_crit_edge);
  
  // Block for.end7 (label_for_end7)
  ReturnInst::Create(mod->getContext(), label_for_end7);
  
  // Resolve Forward References
  fwdref_227->replaceAllUsesWith(int32_inc); delete fwdref_227;
  fwdref_222->replaceAllUsesWith(int32_inc6); delete fwdref_222;
  
 }
 
 // Function: convolve_arr_indirection (func_convolve_arr_indirection)
 {
  Function::arg_iterator args = func_convolve_arr_indirection->arg_begin();
  Value* ptr_in_242 = args++;
  ptr_in_242->setName("in");
  Value* ptr_out_243 = args++;
  ptr_out_243->setName("out");
  Value* ptr_kernel_244 = args++;
  ptr_kernel_244->setName("kernel");
  Value* int32_kn_245 = args++;
  int32_kn_245->setName("kn");
  Value* int32_dim_x_246 = args++;
  int32_dim_x_246->setName("dim_x");
  Value* int32_dim_y_247 = args++;
  int32_dim_y_247->setName("dim_y");
  
  BasicBlock* label_entry_248 = BasicBlock::Create(mod->getContext(), "entry",func_convolve_arr_indirection,0);
  BasicBlock* label_for_body_lr_ph_249 = BasicBlock::Create(mod->getContext(), "for.body.lr.ph",func_convolve_arr_indirection,0);
  BasicBlock* label_for_body_250 = BasicBlock::Create(mod->getContext(), "for.body",func_convolve_arr_indirection,0);
  BasicBlock* label_for_body4_lr_ph_251 = BasicBlock::Create(mod->getContext(), "for.body4.lr.ph",func_convolve_arr_indirection,0);
  BasicBlock* label_for_body4_252 = BasicBlock::Create(mod->getContext(), "for.body4",func_convolve_arr_indirection,0);
  BasicBlock* label_for_inc_253 = BasicBlock::Create(mod->getContext(), "for.inc",func_convolve_arr_indirection,0);
  BasicBlock* label_for_cond1_for_end_crit_edge_254 = BasicBlock::Create(mod->getContext(), "for.cond1.for.end_crit_edge",func_convolve_arr_indirection,0);
  BasicBlock* label_for_end_255 = BasicBlock::Create(mod->getContext(), "for.end",func_convolve_arr_indirection,0);
  BasicBlock* label_for_inc5_256 = BasicBlock::Create(mod->getContext(), "for.inc5",func_convolve_arr_indirection,0);
  BasicBlock* label_for_cond_for_end7_crit_edge_257 = BasicBlock::Create(mod->getContext(), "for.cond.for.end7_crit_edge",func_convolve_arr_indirection,0);
  BasicBlock* label_for_end7_258 = BasicBlock::Create(mod->getContext(), "for.end7",func_convolve_arr_indirection,0);
  
  // Block entry (label_entry_248)
  std::vector<Value*> void_259_params;
  void_259_params.push_back(other_260);
  void_259_params.push_back(const_int64_12);
  void_259_params.push_back(other_261);
  void_259_params.push_back(other_21);
  CallInst* void_259 = CallInst::Create(func_llvm_dbg_value, void_259_params, "", label_entry_248);
  void_259->setCallingConv(CallingConv::C);
  void_259->setTailCall(false);
  AttributeSet void_259_PAL;
  void_259->setAttributes(void_259_PAL);
  
  std::vector<Value*> void_262_params;
  void_262_params.push_back(other_263);
  void_262_params.push_back(const_int64_12);
  void_262_params.push_back(other_264);
  void_262_params.push_back(other_21);
  CallInst* void_262 = CallInst::Create(func_llvm_dbg_value, void_262_params, "", label_entry_248);
  void_262->setCallingConv(CallingConv::C);
  void_262->setTailCall(false);
  AttributeSet void_262_PAL;
  void_262->setAttributes(void_262_PAL);
  
  std::vector<Value*> void_265_params;
  void_265_params.push_back(other_266);
  void_265_params.push_back(const_int64_12);
  void_265_params.push_back(other_267);
  void_265_params.push_back(other_21);
  CallInst* void_265 = CallInst::Create(func_llvm_dbg_value, void_265_params, "", label_entry_248);
  void_265->setCallingConv(CallingConv::C);
  void_265->setTailCall(false);
  AttributeSet void_265_PAL;
  void_265->setAttributes(void_265_PAL);
  
  std::vector<Value*> void_268_params;
  void_268_params.push_back(other_269);
  void_268_params.push_back(const_int64_12);
  void_268_params.push_back(other_270);
  void_268_params.push_back(other_21);
  CallInst* void_268 = CallInst::Create(func_llvm_dbg_value, void_268_params, "", label_entry_248);
  void_268->setCallingConv(CallingConv::C);
  void_268->setTailCall(false);
  AttributeSet void_268_PAL;
  void_268->setAttributes(void_268_PAL);
  
  std::vector<Value*> void_271_params;
  void_271_params.push_back(other_272);
  void_271_params.push_back(const_int64_12);
  void_271_params.push_back(other_273);
  void_271_params.push_back(other_21);
  CallInst* void_271 = CallInst::Create(func_llvm_dbg_value, void_271_params, "", label_entry_248);
  void_271->setCallingConv(CallingConv::C);
  void_271->setTailCall(false);
  AttributeSet void_271_PAL;
  void_271->setAttributes(void_271_PAL);
  
  std::vector<Value*> void_274_params;
  void_274_params.push_back(other_275);
  void_274_params.push_back(const_int64_12);
  void_274_params.push_back(other_276);
  void_274_params.push_back(other_21);
  CallInst* void_274 = CallInst::Create(func_llvm_dbg_value, void_274_params, "", label_entry_248);
  void_274->setCallingConv(CallingConv::C);
  void_274->setTailCall(false);
  AttributeSet void_274_PAL;
  void_274->setAttributes(void_274_PAL);
  
  BinaryOperator* int32_div_277 = BinaryOperator::Create(Instruction::SDiv, int32_kn_245, const_int32_13, "div", label_entry_248);
  std::vector<Value*> void_278_params;
  void_278_params.push_back(other_279);
  void_278_params.push_back(const_int64_12);
  void_278_params.push_back(other_280);
  void_278_params.push_back(other_21);
  CallInst* void_278 = CallInst::Create(func_llvm_dbg_value, void_278_params, "", label_entry_248);
  void_278->setCallingConv(CallingConv::C);
  void_278->setTailCall(false);
  AttributeSet void_278_PAL;
  void_278->setAttributes(void_278_PAL);
  
  std::vector<Value*> void_281_params;
  void_281_params.push_back(other_279);
  void_281_params.push_back(const_int64_12);
  void_281_params.push_back(other_282);
  void_281_params.push_back(other_21);
  CallInst* void_281 = CallInst::Create(func_llvm_dbg_value, void_281_params, "", label_entry_248);
  void_281->setCallingConv(CallingConv::C);
  void_281->setTailCall(false);
  AttributeSet void_281_PAL;
  void_281->setAttributes(void_281_PAL);
  
  BinaryOperator* int32_sub_283 = BinaryOperator::Create(Instruction::Sub, int32_dim_x_246, int32_div_277, "sub", label_entry_248);
  ICmpInst* int1_cmp4_284 = new ICmpInst(*label_entry_248, ICmpInst::ICMP_SLT, int32_div_277, int32_sub_283, "cmp4");
  BranchInst::Create(label_for_body_lr_ph_249, label_for_end7_258, int1_cmp4_284, label_entry_248);
  
  // Block for.body.lr.ph (label_for_body_lr_ph_249)
  BranchInst::Create(label_for_body_250, label_for_body_lr_ph_249);
  
  // Block for.body (label_for_body_250)
  Argument* fwdref_288 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_m_05_287 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "m.05", label_for_body_250);
  int32_m_05_287->addIncoming(int32_div_277, label_for_body_lr_ph_249);
  int32_m_05_287->addIncoming(fwdref_288, label_for_inc5_256);
  
  std::vector<Value*> void_289_params;
  void_289_params.push_back(other_279);
  void_289_params.push_back(const_int64_12);
  void_289_params.push_back(other_290);
  void_289_params.push_back(other_21);
  CallInst* void_289 = CallInst::Create(func_llvm_dbg_value, void_289_params, "", label_for_body_250);
  void_289->setCallingConv(CallingConv::C);
  void_289->setTailCall(false);
  AttributeSet void_289_PAL;
  void_289->setAttributes(void_289_PAL);
  
  BinaryOperator* int32_sub2_291 = BinaryOperator::Create(Instruction::Sub, int32_dim_y_247, int32_div_277, "sub2", label_for_body_250);
  ICmpInst* int1_cmp31_292 = new ICmpInst(*label_for_body_250, ICmpInst::ICMP_SLT, int32_div_277, int32_sub2_291, "cmp31");
  BranchInst::Create(label_for_body4_lr_ph_251, label_for_end_255, int1_cmp31_292, label_for_body_250);
  
  // Block for.body4.lr.ph (label_for_body4_lr_ph_251)
  BranchInst::Create(label_for_body4_252, label_for_body4_lr_ph_251);
  
  // Block for.body4 (label_for_body4_252)
  Argument* fwdref_296 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_n_02_295 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "n.02", label_for_body4_252);
  int32_n_02_295->addIncoming(int32_div_277, label_for_body4_lr_ph_251);
  int32_n_02_295->addIncoming(fwdref_296, label_for_inc_253);
  
  std::vector<Value*> void_297_params;
  void_297_params.push_back(ptr_in_242);
  void_297_params.push_back(ptr_out_243);
  void_297_params.push_back(ptr_kernel_244);
  void_297_params.push_back(int32_kn_245);
  void_297_params.push_back(int32_n_02_295);
  void_297_params.push_back(int32_m_05_287);
  CallInst* void_297 = CallInst::Create(func_filter_kernel_2d, void_297_params, "", label_for_body4_252);
  void_297->setCallingConv(CallingConv::C);
  void_297->setTailCall(false);
  AttributeSet void_297_PAL;
  void_297->setAttributes(void_297_PAL);
  
  BranchInst::Create(label_for_inc_253, label_for_body4_252);
  
  // Block for.inc (label_for_inc_253)
  BinaryOperator* int32_inc_299 = BinaryOperator::Create(Instruction::Add, int32_n_02_295, const_int32_17, "inc", label_for_inc_253);
  std::vector<Value*> void_300_params;
  void_300_params.push_back(other_301);
  void_300_params.push_back(const_int64_12);
  void_300_params.push_back(other_290);
  void_300_params.push_back(other_21);
  CallInst* void_300 = CallInst::Create(func_llvm_dbg_value, void_300_params, "", label_for_inc_253);
  void_300->setCallingConv(CallingConv::C);
  void_300->setTailCall(false);
  AttributeSet void_300_PAL;
  void_300->setAttributes(void_300_PAL);
  
  ICmpInst* int1_cmp3_302 = new ICmpInst(*label_for_inc_253, ICmpInst::ICMP_SLT, int32_inc_299, int32_sub2_291, "cmp3");
  BranchInst::Create(label_for_body4_252, label_for_cond1_for_end_crit_edge_254, int1_cmp3_302, label_for_inc_253);
  
  // Block for.cond1.for.end_crit_edge (label_for_cond1_for_end_crit_edge_254)
  BranchInst::Create(label_for_end_255, label_for_cond1_for_end_crit_edge_254);
  
  // Block for.end (label_for_end_255)
  BranchInst::Create(label_for_inc5_256, label_for_end_255);
  
  // Block for.inc5 (label_for_inc5_256)
  BinaryOperator* int32_inc6_306 = BinaryOperator::Create(Instruction::Add, int32_m_05_287, const_int32_17, "inc6", label_for_inc5_256);
  std::vector<Value*> void_307_params;
  void_307_params.push_back(other_308);
  void_307_params.push_back(const_int64_12);
  void_307_params.push_back(other_282);
  void_307_params.push_back(other_21);
  CallInst* void_307 = CallInst::Create(func_llvm_dbg_value, void_307_params, "", label_for_inc5_256);
  void_307->setCallingConv(CallingConv::C);
  void_307->setTailCall(false);
  AttributeSet void_307_PAL;
  void_307->setAttributes(void_307_PAL);
  
  ICmpInst* int1_cmp_309 = new ICmpInst(*label_for_inc5_256, ICmpInst::ICMP_SLT, int32_inc6_306, int32_sub_283, "cmp");
  BranchInst::Create(label_for_body_250, label_for_cond_for_end7_crit_edge_257, int1_cmp_309, label_for_inc5_256);
  
  // Block for.cond.for.end7_crit_edge (label_for_cond_for_end7_crit_edge_257)
  BranchInst::Create(label_for_end7_258, label_for_cond_for_end7_crit_edge_257);
  
  // Block for.end7 (label_for_end7_258)
  ReturnInst::Create(mod->getContext(), label_for_end7_258);
  
  // Resolve Forward References
  fwdref_296->replaceAllUsesWith(int32_inc_299); delete fwdref_296;
  fwdref_288->replaceAllUsesWith(int32_inc6_306); delete fwdref_288;
  
 }
 
 // Function: convolve_loop_nest (func_convolve_loop_nest)
 {
  Function::arg_iterator args = func_convolve_loop_nest->arg_begin();
  Value* ptr_in_313 = args++;
  ptr_in_313->setName("in");
  Value* ptr_out_314 = args++;
  ptr_out_314->setName("out");
  Value* ptr_kernel_315 = args++;
  ptr_kernel_315->setName("kernel");
  Value* int32_kn_316 = args++;
  int32_kn_316->setName("kn");
  Value* int32_dim_x_317 = args++;
  int32_dim_x_317->setName("dim_x");
  Value* int32_dim_y_318 = args++;
  int32_dim_y_318->setName("dim_y");
  
  BasicBlock* label_entry_319 = BasicBlock::Create(mod->getContext(), "entry",func_convolve_loop_nest,0);
  BasicBlock* label_for_body_lr_ph_320 = BasicBlock::Create(mod->getContext(), "for.body.lr.ph",func_convolve_loop_nest,0);
  BasicBlock* label_for_body_321 = BasicBlock::Create(mod->getContext(), "for.body",func_convolve_loop_nest,0);
  BasicBlock* label_for_body4_lr_ph_322 = BasicBlock::Create(mod->getContext(), "for.body4.lr.ph",func_convolve_loop_nest,0);
  BasicBlock* label_for_body4_323 = BasicBlock::Create(mod->getContext(), "for.body4",func_convolve_loop_nest,0);
  BasicBlock* label_for_body8_lr_ph = BasicBlock::Create(mod->getContext(), "for.body8.lr.ph",func_convolve_loop_nest,0);
  BasicBlock* label_for_body8 = BasicBlock::Create(mod->getContext(), "for.body8",func_convolve_loop_nest,0);
  BasicBlock* label_for_body12_lr_ph = BasicBlock::Create(mod->getContext(), "for.body12.lr.ph",func_convolve_loop_nest,0);
  BasicBlock* label_for_body12 = BasicBlock::Create(mod->getContext(), "for.body12",func_convolve_loop_nest,0);
  BasicBlock* label_for_inc_324 = BasicBlock::Create(mod->getContext(), "for.inc",func_convolve_loop_nest,0);
  BasicBlock* label_for_cond10_for_end_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond10.for.end_crit_edge",func_convolve_loop_nest,0);
  BasicBlock* label_for_end_325 = BasicBlock::Create(mod->getContext(), "for.end",func_convolve_loop_nest,0);
  BasicBlock* label_for_inc21 = BasicBlock::Create(mod->getContext(), "for.inc21",func_convolve_loop_nest,0);
  BasicBlock* label_for_cond6_for_end23_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond6.for.end23_crit_edge",func_convolve_loop_nest,0);
  BasicBlock* label_for_end23 = BasicBlock::Create(mod->getContext(), "for.end23",func_convolve_loop_nest,0);
  BasicBlock* label_for_inc29 = BasicBlock::Create(mod->getContext(), "for.inc29",func_convolve_loop_nest,0);
  BasicBlock* label_for_cond1_for_end31_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond1.for.end31_crit_edge",func_convolve_loop_nest,0);
  BasicBlock* label_for_end31 = BasicBlock::Create(mod->getContext(), "for.end31",func_convolve_loop_nest,0);
  BasicBlock* label_for_inc32 = BasicBlock::Create(mod->getContext(), "for.inc32",func_convolve_loop_nest,0);
  BasicBlock* label_for_cond_for_end34_crit_edge = BasicBlock::Create(mod->getContext(), "for.cond.for.end34_crit_edge",func_convolve_loop_nest,0);
  BasicBlock* label_for_end34 = BasicBlock::Create(mod->getContext(), "for.end34",func_convolve_loop_nest,0);
  
  // Block entry (label_entry_319)
  std::vector<Value*> void_326_params;
  void_326_params.push_back(other_327);
  void_326_params.push_back(const_int64_12);
  void_326_params.push_back(other_328);
  void_326_params.push_back(other_21);
  CallInst* void_326 = CallInst::Create(func_llvm_dbg_value, void_326_params, "", label_entry_319);
  void_326->setCallingConv(CallingConv::C);
  void_326->setTailCall(false);
  AttributeSet void_326_PAL;
  void_326->setAttributes(void_326_PAL);
  
  std::vector<Value*> void_329_params;
  void_329_params.push_back(other_330);
  void_329_params.push_back(const_int64_12);
  void_329_params.push_back(other_331);
  void_329_params.push_back(other_21);
  CallInst* void_329 = CallInst::Create(func_llvm_dbg_value, void_329_params, "", label_entry_319);
  void_329->setCallingConv(CallingConv::C);
  void_329->setTailCall(false);
  AttributeSet void_329_PAL;
  void_329->setAttributes(void_329_PAL);
  
  std::vector<Value*> void_332_params;
  void_332_params.push_back(other_333);
  void_332_params.push_back(const_int64_12);
  void_332_params.push_back(other_334);
  void_332_params.push_back(other_21);
  CallInst* void_332 = CallInst::Create(func_llvm_dbg_value, void_332_params, "", label_entry_319);
  void_332->setCallingConv(CallingConv::C);
  void_332->setTailCall(false);
  AttributeSet void_332_PAL;
  void_332->setAttributes(void_332_PAL);
  
  std::vector<Value*> void_335_params;
  void_335_params.push_back(other_336);
  void_335_params.push_back(const_int64_12);
  void_335_params.push_back(other_337);
  void_335_params.push_back(other_21);
  CallInst* void_335 = CallInst::Create(func_llvm_dbg_value, void_335_params, "", label_entry_319);
  void_335->setCallingConv(CallingConv::C);
  void_335->setTailCall(false);
  AttributeSet void_335_PAL;
  void_335->setAttributes(void_335_PAL);
  
  std::vector<Value*> void_338_params;
  void_338_params.push_back(other_339);
  void_338_params.push_back(const_int64_12);
  void_338_params.push_back(other_340);
  void_338_params.push_back(other_21);
  CallInst* void_338 = CallInst::Create(func_llvm_dbg_value, void_338_params, "", label_entry_319);
  void_338->setCallingConv(CallingConv::C);
  void_338->setTailCall(false);
  AttributeSet void_338_PAL;
  void_338->setAttributes(void_338_PAL);
  
  std::vector<Value*> void_341_params;
  void_341_params.push_back(other_342);
  void_341_params.push_back(const_int64_12);
  void_341_params.push_back(other_343);
  void_341_params.push_back(other_21);
  CallInst* void_341 = CallInst::Create(func_llvm_dbg_value, void_341_params, "", label_entry_319);
  void_341->setCallingConv(CallingConv::C);
  void_341->setTailCall(false);
  AttributeSet void_341_PAL;
  void_341->setAttributes(void_341_PAL);
  
  BinaryOperator* int32_div_344 = BinaryOperator::Create(Instruction::SDiv, int32_kn_316, const_int32_13, "div", label_entry_319);
  std::vector<Value*> void_345_params;
  void_345_params.push_back(other_346);
  void_345_params.push_back(const_int64_12);
  void_345_params.push_back(other_347);
  void_345_params.push_back(other_21);
  CallInst* void_345 = CallInst::Create(func_llvm_dbg_value, void_345_params, "", label_entry_319);
  void_345->setCallingConv(CallingConv::C);
  void_345->setTailCall(false);
  AttributeSet void_345_PAL;
  void_345->setAttributes(void_345_PAL);
  
  std::vector<Value*> void_348_params;
  void_348_params.push_back(other_346);
  void_348_params.push_back(const_int64_12);
  void_348_params.push_back(other_349);
  void_348_params.push_back(other_21);
  CallInst* void_348 = CallInst::Create(func_llvm_dbg_value, void_348_params, "", label_entry_319);
  void_348->setCallingConv(CallingConv::C);
  void_348->setTailCall(false);
  AttributeSet void_348_PAL;
  void_348->setAttributes(void_348_PAL);
  
  BinaryOperator* int32_350 = BinaryOperator::Create(Instruction::Sub, const_int32_14, int32_div_344, "", label_entry_319);
  CastInst* int64_351 = new SExtInst(int32_350, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  CastInst* int64_352 = new SExtInst(int32_div_344, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  CastInst* int64_353 = new SExtInst(int32_350, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  CastInst* int64_354 = new SExtInst(int32_div_344, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  CastInst* int64_355 = new SExtInst(int32_div_344, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  CastInst* int64_356 = new SExtInst(int32_div_344, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  BinaryOperator* int32_sub_357 = BinaryOperator::Create(Instruction::Sub, int32_dim_x_317, int32_div_344, "sub", label_entry_319);
  CastInst* int64_358 = new SExtInst(int32_sub_357, IntegerType::get(mod->getContext(), 64), "", label_entry_319);
  ICmpInst* int1_cmp22 = new ICmpInst(*label_entry_319, ICmpInst::ICMP_SLT, int64_356, int64_358, "cmp22");
  BranchInst::Create(label_for_body_lr_ph_320, label_for_end34, int1_cmp22, label_entry_319);
  
  // Block for.body.lr.ph (label_for_body_lr_ph_320)
  BranchInst::Create(label_for_body_321, label_for_body_lr_ph_320);
  
  // Block for.body (label_for_body_321)
  Argument* fwdref_361 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv23 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv23", label_for_body_321);
  int64_indvars_iv23->addIncoming(int64_356, label_for_body_lr_ph_320);
  int64_indvars_iv23->addIncoming(fwdref_361, label_for_inc32);
  
  std::vector<Value*> void_362_params;
  void_362_params.push_back(other_346);
  void_362_params.push_back(const_int64_12);
  void_362_params.push_back(other_363);
  void_362_params.push_back(other_21);
  CallInst* void_362 = CallInst::Create(func_llvm_dbg_value, void_362_params, "", label_for_body_321);
  void_362->setCallingConv(CallingConv::C);
  void_362->setTailCall(false);
  AttributeSet void_362_PAL;
  void_362->setAttributes(void_362_PAL);
  
  BinaryOperator* int32_sub2_364 = BinaryOperator::Create(Instruction::Sub, int32_dim_y_318, int32_div_344, "sub2", label_for_body_321);
  CastInst* int64_365 = new SExtInst(int32_sub2_364, IntegerType::get(mod->getContext(), 64), "", label_for_body_321);
  ICmpInst* int1_cmp318 = new ICmpInst(*label_for_body_321, ICmpInst::ICMP_SLT, int64_355, int64_365, "cmp318");
  BranchInst::Create(label_for_body4_lr_ph_322, label_for_end31, int1_cmp318, label_for_body_321);
  
  // Block for.body4.lr.ph (label_for_body4_lr_ph_322)
  BranchInst::Create(label_for_body4_323, label_for_body4_lr_ph_322);
  
  // Block for.body4 (label_for_body4_323)
  Argument* fwdref_368 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv19 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv19", label_for_body4_323);
  int64_indvars_iv19->addIncoming(int64_355, label_for_body4_lr_ph_322);
  int64_indvars_iv19->addIncoming(fwdref_368, label_for_inc29);
  
  std::vector<Value*> void_369_params;
  void_369_params.push_back(other_47);
  void_369_params.push_back(const_int64_12);
  void_369_params.push_back(other_370);
  void_369_params.push_back(other_21);
  CallInst* void_369 = CallInst::Create(func_llvm_dbg_value, void_369_params, "", label_for_body4_323);
  void_369->setCallingConv(CallingConv::C);
  void_369->setTailCall(false);
  AttributeSet void_369_PAL;
  void_369->setAttributes(void_369_PAL);
  
  std::vector<Value*> void_371_params;
  void_371_params.push_back(other_50);
  void_371_params.push_back(const_int64_12);
  void_371_params.push_back(other_372);
  void_371_params.push_back(other_21);
  CallInst* void_371 = CallInst::Create(func_llvm_dbg_value, void_371_params, "", label_for_body4_323);
  void_371->setCallingConv(CallingConv::C);
  void_371->setTailCall(false);
  AttributeSet void_371_PAL;
  void_371->setAttributes(void_371_PAL);
  
  std::vector<Value*> void_373_params;
  void_373_params.push_back(other_68);
  void_373_params.push_back(const_int64_12);
  void_373_params.push_back(other_374);
  void_373_params.push_back(other_21);
  CallInst* void_373 = CallInst::Create(func_llvm_dbg_value, void_373_params, "", label_for_body4_323);
  void_373->setCallingConv(CallingConv::C);
  void_373->setTailCall(false);
  AttributeSet void_373_PAL;
  void_373->setAttributes(void_373_PAL);
  
  ICmpInst* int1_cmp711 = new ICmpInst(*label_for_body4_323, ICmpInst::ICMP_SLE, int64_353, int64_354, "cmp711");
  BranchInst::Create(label_for_body8_lr_ph, label_for_end23, int1_cmp711, label_for_body4_323);
  
  // Block for.body8.lr.ph (label_for_body8_lr_ph)
  BranchInst::Create(label_for_body8, label_for_body8_lr_ph);
  
  // Block for.body8 (label_for_body8)
  Argument* fwdref_378 = new Argument(IntegerType::get(mod->getContext(), 32));
  PHINode* int32_c_015_377 = PHINode::Create(IntegerType::get(mod->getContext(), 32), 2, "c.015", label_for_body8);
  int32_c_015_377->addIncoming(const_int32_14, label_for_body8_lr_ph);
  int32_c_015_377->addIncoming(fwdref_378, label_for_inc21);
  
  Argument* fwdref_380 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_014_379 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.014", label_for_body8);
  float_pixel_014_379->addIncoming(const_float_15, label_for_body8_lr_ph);
  float_pixel_014_379->addIncoming(fwdref_380, label_for_inc21);
  
  Argument* fwdref_382 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv12_381 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv12", label_for_body8);
  int64_indvars_iv12_381->addIncoming(int64_353, label_for_body8_lr_ph);
  int64_indvars_iv12_381->addIncoming(fwdref_382, label_for_inc21);
  
  std::vector<Value*> void_383_params;
  void_383_params.push_back(other_68);
  void_383_params.push_back(const_int64_12);
  void_383_params.push_back(other_384);
  void_383_params.push_back(other_21);
  CallInst* void_383 = CallInst::Create(func_llvm_dbg_value, void_383_params, "", label_for_body8);
  void_383->setCallingConv(CallingConv::C);
  void_383->setTailCall(false);
  AttributeSet void_383_PAL;
  void_383->setAttributes(void_383_PAL);
  
  CastInst* int64_385 = new SExtInst(int32_c_015_377, IntegerType::get(mod->getContext(), 64), "", label_for_body8);
  ICmpInst* int1_cmp114 = new ICmpInst(*label_for_body8, ICmpInst::ICMP_SLE, int64_351, int64_352, "cmp114");
  BranchInst::Create(label_for_body12_lr_ph, label_for_end_325, int1_cmp114, label_for_body8);
  
  // Block for.body12.lr.ph (label_for_body12_lr_ph)
  BranchInst::Create(label_for_body12, label_for_body12_lr_ph);
  
  // Block for.body12 (label_for_body12)
  Argument* fwdref_389 = new Argument(Type::getFloatTy(mod->getContext()));
  PHINode* float_pixel_17_388 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.17", label_for_body12);
  float_pixel_17_388->addIncoming(float_pixel_014_379, label_for_body12_lr_ph);
  float_pixel_17_388->addIncoming(fwdref_389, label_for_inc_324);
  
  Argument* fwdref_391 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv6_390 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv6", label_for_body12);
  int64_indvars_iv6_390->addIncoming(int64_385, label_for_body12_lr_ph);
  int64_indvars_iv6_390->addIncoming(fwdref_391, label_for_inc_324);
  
  Argument* fwdref_393 = new Argument(IntegerType::get(mod->getContext(), 64));
  PHINode* int64_indvars_iv15_392 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv15", label_for_body12);
  int64_indvars_iv15_392->addIncoming(int64_351, label_for_body12_lr_ph);
  int64_indvars_iv15_392->addIncoming(fwdref_393, label_for_inc_324);
  
  BinaryOperator* int64_394 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv23, int64_indvars_iv15_392, "", label_for_body12);
  BinaryOperator* int64_395 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv19, int64_indvars_iv12_381, "", label_for_body12);
  GetElementPtrInst* ptr_arrayidx_396 = GetElementPtrInst::Create(ptr_in_313, int64_395, "arrayidx", label_for_body12);
  LoadInst* ptr_397 = new LoadInst(ptr_arrayidx_396, "", false, label_for_body12);
  ptr_397->setAlignment(8);
  GetElementPtrInst* ptr_arrayidx15 = GetElementPtrInst::Create(ptr_397, int64_394, "arrayidx15", label_for_body12);
  LoadInst* int8_398 = new LoadInst(ptr_arrayidx15, "", false, label_for_body12);
  int8_398->setAlignment(1);
  CastInst* int32_conv_399 = new ZExtInst(int8_398, IntegerType::get(mod->getContext(), 32), "conv", label_for_body12);
  CastInst* float_conv16 = new SIToFPInst(int32_conv_399, Type::getFloatTy(mod->getContext()), "conv16", label_for_body12);
  BinaryOperator* int64_indvars_iv_next_400 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv6_390, const_int64_16, "indvars.iv.next", label_for_body12);
  std::vector<Value*> void_401_params;
  void_401_params.push_back(other_68);
  void_401_params.push_back(const_int64_12);
  void_401_params.push_back(other_372);
  void_401_params.push_back(other_21);
  CallInst* void_401 = CallInst::Create(func_llvm_dbg_value, void_401_params, "", label_for_body12);
  void_401->setCallingConv(CallingConv::C);
  void_401->setTailCall(false);
  AttributeSet void_401_PAL;
  void_401->setAttributes(void_401_PAL);
  
  GetElementPtrInst* ptr_arrayidx18 = GetElementPtrInst::Create(ptr_kernel_315, int64_indvars_iv6_390, "arrayidx18", label_for_body12);
  LoadInst* float_402 = new LoadInst(ptr_arrayidx18, "", false, label_for_body12);
  float_402->setAlignment(4);
  BinaryOperator* float_mul_403 = BinaryOperator::Create(Instruction::FMul, float_conv16, float_402, "mul", label_for_body12);
  BinaryOperator* float_add19 = BinaryOperator::Create(Instruction::FAdd, float_pixel_17_388, float_mul_403, "add19", label_for_body12);
  std::vector<Value*> void_404_params;
  void_404_params.push_back(other_405);
  void_404_params.push_back(const_int64_12);
  void_404_params.push_back(other_370);
  void_404_params.push_back(other_21);
  CallInst* void_404 = CallInst::Create(func_llvm_dbg_value, void_404_params, "", label_for_body12);
  void_404->setCallingConv(CallingConv::C);
  void_404->setTailCall(false);
  AttributeSet void_404_PAL;
  void_404->setAttributes(void_404_PAL);
  
  BranchInst::Create(label_for_inc_324, label_for_body12);
  
  // Block for.inc (label_for_inc_324)
  BinaryOperator* int64_indvars_iv_next2_407 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv15_392, const_int64_16, "indvars.iv.next2", label_for_inc_324);
  std::vector<Value*> void_408_params;
  void_408_params.push_back(other_68);
  void_408_params.push_back(const_int64_12);
  void_408_params.push_back(other_384);
  void_408_params.push_back(other_21);
  CallInst* void_408 = CallInst::Create(func_llvm_dbg_value, void_408_params, "", label_for_inc_324);
  void_408->setCallingConv(CallingConv::C);
  void_408->setTailCall(false);
  AttributeSet void_408_PAL;
  void_408->setAttributes(void_408_PAL);
  
  ICmpInst* int1_cmp11_409 = new ICmpInst(*label_for_inc_324, ICmpInst::ICMP_SLE, int64_indvars_iv_next2_407, int64_352, "cmp11");
  BranchInst::Create(label_for_body12, label_for_cond10_for_end_crit_edge, int1_cmp11_409, label_for_inc_324);
  
  // Block for.cond10.for.end_crit_edge (label_for_cond10_for_end_crit_edge)
  PHINode* int64_split_411 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 1, "split", label_for_cond10_for_end_crit_edge);
  int64_split_411->addIncoming(int64_indvars_iv_next_400, label_for_inc_324);
  
  PHINode* float_split8_412 = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split8", label_for_cond10_for_end_crit_edge);
  float_split8_412->addIncoming(float_add19, label_for_inc_324);
  
  BranchInst::Create(label_for_end_325, label_for_cond10_for_end_crit_edge);
  
  // Block for.end (label_for_end_325)
  PHINode* int64_indvars_iv13_414 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv13", label_for_end_325);
  int64_indvars_iv13_414->addIncoming(int64_indvars_iv12_381, label_for_cond10_for_end_crit_edge);
  int64_indvars_iv13_414->addIncoming(int64_indvars_iv12_381, label_for_body8);
  
  PHINode* int64_c_1_lcssa_wide_415 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "c.1.lcssa.wide", label_for_end_325);
  int64_c_1_lcssa_wide_415->addIncoming(int64_split_411, label_for_cond10_for_end_crit_edge);
  int64_c_1_lcssa_wide_415->addIncoming(int64_385, label_for_body8);
  
  PHINode* float_pixel_1_lcssa_416 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.1.lcssa", label_for_end_325);
  float_pixel_1_lcssa_416->addIncoming(float_split8_412, label_for_cond10_for_end_crit_edge);
  float_pixel_1_lcssa_416->addIncoming(float_pixel_014_379, label_for_body8);
  
  CastInst* int32_417 = new TruncInst(int64_c_1_lcssa_wide_415, IntegerType::get(mod->getContext(), 32), "", label_for_end_325);
  BranchInst::Create(label_for_inc21, label_for_end_325);
  
  // Block for.inc21 (label_for_inc21)
  BinaryOperator* int64_indvars_iv_next9_419 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv13_414, const_int64_16, "indvars.iv.next9", label_for_inc21);
  std::vector<Value*> void_420_params;
  void_420_params.push_back(other_68);
  void_420_params.push_back(const_int64_12);
  void_420_params.push_back(other_374);
  void_420_params.push_back(other_21);
  CallInst* void_420 = CallInst::Create(func_llvm_dbg_value, void_420_params, "", label_for_inc21);
  void_420->setCallingConv(CallingConv::C);
  void_420->setTailCall(false);
  AttributeSet void_420_PAL;
  void_420->setAttributes(void_420_PAL);
  
  ICmpInst* int1_cmp7 = new ICmpInst(*label_for_inc21, ICmpInst::ICMP_SLE, int64_indvars_iv_next9_419, int64_354, "cmp7");
  BranchInst::Create(label_for_body8, label_for_cond6_for_end23_crit_edge, int1_cmp7, label_for_inc21);
  
  // Block for.cond6.for.end23_crit_edge (label_for_cond6_for_end23_crit_edge)
  PHINode* float_split16_422 = PHINode::Create(Type::getFloatTy(mod->getContext()), 1, "split16", label_for_cond6_for_end23_crit_edge);
  float_split16_422->addIncoming(float_pixel_1_lcssa_416, label_for_inc21);
  
  BranchInst::Create(label_for_end23, label_for_cond6_for_end23_crit_edge);
  
  // Block for.end23 (label_for_end23)
  PHINode* int64_indvars_iv20 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv20", label_for_end23);
  int64_indvars_iv20->addIncoming(int64_indvars_iv19, label_for_cond6_for_end23_crit_edge);
  int64_indvars_iv20->addIncoming(int64_indvars_iv19, label_for_body4_323);
  
  PHINode* float_pixel_0_lcssa_424 = PHINode::Create(Type::getFloatTy(mod->getContext()), 2, "pixel.0.lcssa", label_for_end23);
  float_pixel_0_lcssa_424->addIncoming(float_split16_422, label_for_cond6_for_end23_crit_edge);
  float_pixel_0_lcssa_424->addIncoming(const_float_15, label_for_body4_323);
  
  CastInst* int8_conv24 = new FPToUIInst(float_pixel_0_lcssa_424, IntegerType::get(mod->getContext(), 8), "conv24", label_for_end23);
  GetElementPtrInst* ptr_arrayidx27 = GetElementPtrInst::Create(ptr_out_314, int64_indvars_iv20, "arrayidx27", label_for_end23);
  LoadInst* ptr_425 = new LoadInst(ptr_arrayidx27, "", false, label_for_end23);
  ptr_425->setAlignment(8);
  GetElementPtrInst* ptr_arrayidx28 = GetElementPtrInst::Create(ptr_425, int64_indvars_iv23, "arrayidx28", label_for_end23);
  StoreInst* void_426 = new StoreInst(int8_conv24, ptr_arrayidx28, false, label_for_end23);
  void_426->setAlignment(1);
  BranchInst::Create(label_for_inc29, label_for_end23);
  
  // Block for.inc29 (label_for_inc29)
  BinaryOperator* int64_indvars_iv_next17 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv20, const_int64_16, "indvars.iv.next17", label_for_inc29);
  std::vector<Value*> void_428_params;
  void_428_params.push_back(other_68);
  void_428_params.push_back(const_int64_12);
  void_428_params.push_back(other_363);
  void_428_params.push_back(other_21);
  CallInst* void_428 = CallInst::Create(func_llvm_dbg_value, void_428_params, "", label_for_inc29);
  void_428->setCallingConv(CallingConv::C);
  void_428->setTailCall(false);
  AttributeSet void_428_PAL;
  void_428->setAttributes(void_428_PAL);
  
  ICmpInst* int1_cmp3_429 = new ICmpInst(*label_for_inc29, ICmpInst::ICMP_SLT, int64_indvars_iv_next17, int64_365, "cmp3");
  BranchInst::Create(label_for_body4_323, label_for_cond1_for_end31_crit_edge, int1_cmp3_429, label_for_inc29);
  
  // Block for.cond1.for.end31_crit_edge (label_for_cond1_for_end31_crit_edge)
  BranchInst::Create(label_for_end31, label_for_cond1_for_end31_crit_edge);
  
  // Block for.end31 (label_for_end31)
  PHINode* int64_indvars_iv24 = PHINode::Create(IntegerType::get(mod->getContext(), 64), 2, "indvars.iv24", label_for_end31);
  int64_indvars_iv24->addIncoming(int64_indvars_iv23, label_for_cond1_for_end31_crit_edge);
  int64_indvars_iv24->addIncoming(int64_indvars_iv23, label_for_body_321);
  
  BranchInst::Create(label_for_inc32, label_for_end31);
  
  // Block for.inc32 (label_for_inc32)
  BinaryOperator* int64_indvars_iv_next21 = BinaryOperator::Create(Instruction::Add, int64_indvars_iv24, const_int64_16, "indvars.iv.next21", label_for_inc32);
  std::vector<Value*> void_433_params;
  void_433_params.push_back(other_68);
  void_433_params.push_back(const_int64_12);
  void_433_params.push_back(other_349);
  void_433_params.push_back(other_21);
  CallInst* void_433 = CallInst::Create(func_llvm_dbg_value, void_433_params, "", label_for_inc32);
  void_433->setCallingConv(CallingConv::C);
  void_433->setTailCall(false);
  AttributeSet void_433_PAL;
  void_433->setAttributes(void_433_PAL);
  
  ICmpInst* int1_cmp_434 = new ICmpInst(*label_for_inc32, ICmpInst::ICMP_SLT, int64_indvars_iv_next21, int64_358, "cmp");
  BranchInst::Create(label_for_body_321, label_for_cond_for_end34_crit_edge, int1_cmp_434, label_for_inc32);
  
  // Block for.cond.for.end34_crit_edge (label_for_cond_for_end34_crit_edge)
  BranchInst::Create(label_for_end34, label_for_cond_for_end34_crit_edge);
  
  // Block for.end34 (label_for_end34)
  ReturnInst::Create(mod->getContext(), label_for_end34);
  
  // Resolve Forward References
  fwdref_393->replaceAllUsesWith(int64_indvars_iv_next2_407); delete fwdref_393;
  fwdref_382->replaceAllUsesWith(int64_indvars_iv_next9_419); delete fwdref_382;
  fwdref_391->replaceAllUsesWith(int64_indvars_iv_next_400); delete fwdref_391;
  fwdref_389->replaceAllUsesWith(float_add19); delete fwdref_389;
  fwdref_380->replaceAllUsesWith(float_pixel_1_lcssa_416); delete fwdref_380;
  fwdref_378->replaceAllUsesWith(int32_417); delete fwdref_378;
  fwdref_368->replaceAllUsesWith(int64_indvars_iv_next17); delete fwdref_368;
  fwdref_361->replaceAllUsesWith(int64_indvars_iv_next21); delete fwdref_361;
  
 }
 
 return mod;
}
